<?php

namespace ContainerXPWxZip;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_ThOK79MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.ThOK79M' shared service.
     *
     * @return \http\Env\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\EditController::change()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".');
    }
}
