
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'index.html.twig'
tours:
    path: /tours
    controller: App\Controller\ToursController::show