<?php

namespace ContainerX3lFsdb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddToursControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AddToursController' shared autowired service.
     *
     * @return \App\Controller\AddToursController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\AddToursController.php';

        $container->services['App\\Controller\\AddToursController'] = $instance = new \App\Controller\AddToursController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\AddToursController', $container));

        return $instance;
    }
}
