<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0pxsb8p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0pxsb8p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0pxsb8p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0pxsb8p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0pxsb8p\App_KernelDevDebugContainer([
    'container.build_hash' => '0pxsb8p',
    'container.build_id' => '2c4ef9ce',
    'container.build_time' => 1592416342,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0pxsb8p');
