<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRewxO9U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRewxO9U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRewxO9U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRewxO9U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRewxO9U\App_KernelDevDebugContainer([
    'container.build_hash' => 'RewxO9U',
    'container.build_id' => '604570c4',
    'container.build_time' => 1593192874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRewxO9U');
